// action type
export const LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY";
export const REGISTER_SUCCESSFULLY='REGISTER_SUCCESSFULLY';
export const FORGOT_PASSWORD='FORGOT_PASSWORD';
export const RESET_PASSWORD='RESET_PASSWORD';